### ISSUE TITLE
Is it a good idea to render with freetype?

### ISSUE THREAD

**Issue by Benau** [supertuxkart/stk-code#2311]
Hi!

I recently updated the chinese translations (both version), I want to test so I tried to regenerate the fonts, unfortunately some problems come out.

The font tool doesn't work on linux,it can't auto remove unneeded chars (chinese for example), but it's easy to fix. But the generated fonts are too large (~10 pics), I tried to load but Korean was display corruptly, why can't stk just load specific lang xml file? I see some related code comment out in scalable_font.cpp.

*Note, I don't know if it's a problem with my linux font tool.

Anyway, instead of using font png, I tried something more ambitious -- try using libfreetype instead. 

Some advantages gained is that it enables better font display with cyrillic like #2121, or even font selection support(does stk need?), if not too useless typing wildchar in stk input prompt support too.

Also no more font addition is needed for each translation update when the code is ready.

Do devs from stk like this idea? I can do further work on it if you like.

**Comment by auriamg** [comment]
This is potentially interesting, though quite a big change so understandably this is not going in next release :) On which OS did you test? Of course this would need to work on all systems, we'd need to check licenses too

Also, the running of whitespace.py makes the changes a LOT harder to review, I'm trying to check what your changes implies but there's so many whitespace changes there it's hard to tell what actually changed :(

**Comment by Benau** [comment]
I tested on linux of gnome with opensource radeon driver, freeype is available on windows and mac as I see there's a pkg available for them(even guide to compile), also I add freetype in CMakelist so it should work on all.

Let me revert the changes to non-related file and push again.....

**Comment by Benau** [comment]
updated now with same name, should be clearer.

I "think" the deps on windows built tool should include freetype as it's required by the font tool anyway.

For your reference, the CGUITTFont.cpp are used across many oss project like mimetest.

The shadow code are "borrowed" from them, but doesn't work on stk, I will deal with later if you like. Also as you can see, I changed Driver->draw2dImageBatch to draw2dImage like scalablefont in stk as your 2dutils doesn't contain draw2dImageBatch function(should we have draw2dImageBatch too?) , using Driver->draw2dImageBatch to draw doesn't work, do you think I did the convert right?

**Comment by deveee** [comment]
Freetype library is used in sdl2-ttf, which works really nice.

It is dual-licensed. It has it's own a BSD-like license which is 
compatible with GNU GPL 3, but not with GPL 2. And it is released also 
under GPL 2 license, which should be safe for us to use.

**Comment by hiker** [comment]
IIrc the original Tuxkart Project-of-the-Month project partly fell apart because of the use of truetype fonts. It performance was just not fast enough. Unfortunately I can't find a link to confirm this (and I am a bit vague on the details). 

But e.g.:
http://gamedev.stackexchange.com/questions/40385/whats-best-to-use-otf-or-ttf
"Still, fonts in game engines are usually simple bitmaps, for performance reasons. So if you're actually writing a game and performance is an issue, use an offline bitmap font generator as you were suggested in comments."

We have to at least make sure the actual in-game performance is not affected by this. I don't like the idea of having to restart STK if the resolution is changed tbh, I would prefer to fix whatever is causing the crash :)

**Comment by Benau** [comment]
there's more "famous" 3d game using ttf, like alienarena, they implemented their own ttf function.

**Comment by hiker** [comment]
What fps do you get without ttf? For faster graphics card using ttf might be fine, but on cards that are already struggling it might be more of a problem. Iirc hd3000 has the problem of not properly managing vram, so if ttf should increase vram use that might be a bit of a problem.

I would suggest to add another timer so that the time for text rendering can be displayed with the profiler.

It might just be that technology has improved, and we have also reduced the amount of text ;)  We should certainly test the Asian languages (I don't have a computer atm - hopefully in a week I am back), those are the fonts that are most likely to be a problem.

The other thing that might need to be verified is the billboard text like "Leader".

And afaik there is no option to show vram usage :(

**Comment by Benau** [comment]
What fps do you get without ttf?
the same, not much difference. my graphic card is r270

In fact I got a notebook with Radeon HD 6310, I can test more if I implement more function for ttf.

I think it should not  increase vram usage anyway, as the code only preload first 127 char first, and then load more on demand(but need to change, I think I can write a function to cache base on po file for current language).

**Comment by Benau** [comment]
![2015-09-16 01-40-11](https://cloud.githubusercontent.com/assets/3252341/9884746/0a7af0ce-5c14-11e5-80e5-5f0531554860.png)

Progress made so far, using alien arena game creative block font, very lovely!.

Resize and border drawing should be ok now.

Title should(I think, do you?) be ok too when I force stk to do fallback rendering.

Now I tried to reuse the scalable_font loading function, so instead of from xml, the new method is like load ttf and make bitmap and save it to spritebank, emulating bitmap font loading and should not increase vram usage, as the load and make bitmap is done with cpu. The loading time for 2000 char takes around 1 second (ie 1 secs black screen before stk gui prints), but should use a lot less char when load only used by language.

I tried even load almost all utf8 char, it takes about 1 min black screen and stk is playable runable too (on my pc).

![2015-09-16 02-08-43](https://cloud.githubusercontent.com/assets/3252341/9885470/ebf8a462-5c17-11e5-86de-8fca38146c45.png)
Less blurred, hinting from freetype really rocks....

The most difficult to deal with now is to print the char with height offset correctly as irr doesn't know how to handle line like printing "g" or '"' upper or lower."May" (base on my current knowledge in programming) be ok to fix with it using old function from cguittfont.

This is the now idea (sketch):
-----------
void ScalableFont::doReadXmlFile(io::IXMLReader* xml)
{

  FT_Library    library;
  FT_Face       face;
  
  FT_Init_FreeType( &library );
  FT_New_Face( library, "wqy-microhei.ttf", 0, &face );
  FT_Set_Pixel_Sizes(face, 0, 36);

   for ( u32 n = 0; n < 128 ; ++n )
  {
    if (n == 0) continue;
    int idx = FT_Get_Char_Index( face, n);
    if (idx == 0)  continue;

    FT_Set_Pixel_Sizes(face, 0, 36);
    FT_Load_Glyph( face , idx , FT_LOAD_RENDER);
    
    FT_GlyphSlot slot = face->glyph;
	 FT_Bitmap bits = slot->bitmap;


	core::dimension2du d(bits.width + 1, bits.rows + 1);
	core::dimension2du texture_size;


	// Create and load our image now.
	video::IImage* image = 0;
	switch (bits.pixel_mode)
	{
		case FT_PIXEL_MODE_MONO:
		{
			// Create a blank image and fill it with transparent pixels.
			texture_size = d.getOptimalSize(true, true);
			image = Driver->createImage(video::ECF_A1R5G5B5, texture_size);
			image->fill(video::SColor(0, 255, 255, 255));

			// Load the monochrome data in.
			const u32 image_pitch = image->getPitch() / sizeof(u16);
			u16* image_data = (u16*)image->lock();
			u8* glyph_data = bits.buffer;
			for (s32 y = 0; y < bits.rows; ++y)
			{
				u16* row = image_data;
				for (s32 x = 0; x < bits.width; ++x)
				{
					// Monochrome bitmaps store 8 pixels per byte.  The left-most pixel is the bit 0x80.
					// So, we go through the data each bit at a time.
					if ((glyph_data[y * bits.pitch + (x / 8)] & (0x80 >> (x % 8))) != 0)
						*row = 0xFFFF;
					++row;
				}
				image_data += image_pitch;
			}
			image->unlock();
			break;
		}

		case FT_PIXEL_MODE_GRAY:
		{
			// Create our blank image.
			texture_size = d.getOptimalSize(!Driver->queryFeature(video::EVDF_TEXTURE_NPOT), !Driver->queryFeature(video::EVDF_TEXTURE_NSQUARE), true, 0);
			image = Driver->createImage(video::ECF_A8R8G8B8, texture_size);
			image->fill(video::SColor(0, 255, 255, 255));

			// Load the grayscale data in.
			const float gray_count = static_cast<float>(bits.num_grays);
			const u32 image_pitch = image->getPitch() / sizeof(u32);
			u32* image_data = (u32*)image->lock();
			u8* glyph_data = bits.buffer;
			for (s32 y = 0; y < bits.rows; ++y)
			{
				u8* row = glyph_data;
				for (s32 x = 0; x < bits.width; ++x)
				{
					image_data[y * image_pitch + x] |= static_cast<u32>(255.0f * (static_cast<float>(*row++) / gray_count)) << 24;
					//data[y * image_pitch + x] |= ((u32)(*bitsdata++) << 24);
				}
				glyph_data += bits.pitch;
			}
			image->unlock();
			break;
		}
		default:
			// TODO: error message?
			break;
	}

	 SpriteBank->addTextureAsSprite(Driver->addTexture("character",image));
	if (n == 32)
   CharacterMap[(wchar_t)n] =  1; //I don't know why it has to set an value to whitespace to make it displayable,
   else                           //without this hack space at ignored in stk.
   CharacterMap[(wchar_t)n] =  SpriteBank->getSprites().size() -1;
}
       CharacterMap[(wchar_t)173] =  0; //Don't need a glyph for the soft hypen, as it only print when not having enough space.
                                        //And then it will convert to a "-".
       core::array<core::rect<s32> >& rectangle = SpriteBank->getPositions();

       for (unsigned int n = 0 ; n < SpriteBank->getSprites().size(); ++n)
{
    
    SFontArea a;
    a.underhang     = 0;
    a.overhang      = 0;
    a.spriteno      = n;
    a.width = rectangle[n].getWidth();
     // add character to font
    Areas.push_back(a);
  }

**Comment by Benau** [comment]
The most difficult problem (horizontal offset) is mostly fixed, now i have a preview version (with at least proper position display) for anyone  who want to test.

Now the missing function is that metrics->advance (sth like that) like "ll" are too close together and should be fixed.

Also there's kerning problem, but unlike windows which use under/overhang, freetype use sort of kerning table to handle it but some fonts don't provide kerning data (at least the wqy font)... 

I think it's a less important issue.

It is not efficient to load into stk anyway unless u only handle first 128 char, takes this code from alien arena ttf kerning handling for example and you will know what I meant:
...
int			kerning[ TTF_CHARACTERS ][ TTF_CHARACTERS ];
...
```c++
	// Get kerning information
	if ( FT_HAS_KERNING( face ) ) {
		for ( i = 0 ; i < TTF_CHARACTERS ; i ++ ) {
			int j;
			for ( j = 0 ; j < TTF_CHARACTERS ; j ++ ) {
				FT_Vector kvec;
				FT_Get_Kerning( face , glyphs[ i ] , glyphs[ j ] , FT_KERNING_DEFAULT , &kvec );
				fontInt->kerning[ i ][ j ] = kvec.x >> 6;
				if (fontInt->kerning[i][j] + fontInt->widths[i] > font->width)
					font->width = fontInt->kerning[i][j] + fontInt->widths[i];
				if (fontInt->kerning[i][j] + fontInt->widths[j] > font->width)
					font->width = fontInt->kerning[i][j] + fontInt->widths[j];
			}
		}
	} else {
		font->width = font->size;
		memset( fontInt->kerning , 0 , sizeof( fontInt->kerning ) );
	}
```


On some resolution is horizontal offset (y_shift from code) is calculated incorrectly(??), seems that the offset could not be "scaled"(??) , on 1920x1080 mostly fine. 
![2015-09-17 02-49-14](https://cloud.githubusercontent.com/assets/3252341/9914918/cc81696e-5ce6-11e5-91f3-ef0fb60ca445.png)
Do you have any idea?

This is how on 1920x1080, less mis-align.
![2015-09-17 02-50-52](https://cloud.githubusercontent.com/assets/3252341/9914936/ec3a5608-5ce6-11e5-909b-16a485948df7.png)
i18n:
![2015-09-17 03-00-45](https://cloud.githubusercontent.com/assets/3252341/9915212/610755de-5ce8-11e5-82f4-650ec8040a32.png)

This time I used freesans to test, with 2000 char load. But finally only char from current translation should be loaded. I think later work should not increase vram usage, so anyone should be ok to test now regardless of later changes.Remember to rename the font yourself:) 

Here's come a hacking scalable_font.cpp:
---------------
```c++
// Copyright (C) 2002-2015 Nikolaus Gebhardt
// This file is part of the "Irrlicht Engine".
// For conditions of distribution and use, see copyright notice in irrlicht.h

#include "guiengine/scalable_font.hpp"

#include "graphics/2dutils.hpp"
#include "guiengine/engine.hpp"
#include "io/file_manager.hpp"
#include "utils/translation.hpp"

#include <IAttributes.h>
#include <IGUIEnvironment.h>
#include <IGUISpriteBank.h>
#include <IReadFile.h>
#include <IVideoDriver.h>
#include <IXMLReader.h>


#include <ftglyph.h>
#include <iostream>

using namespace std;;

namespace irr
{
namespace gui
{

//! constructor
ScalableFont::ScalableFont(IGUIEnvironment *env, const std::string &filename)
            : Driver(0), SpriteBank(0), Environment(env), WrongCharacter(0),
              MaxHeight(0), GlobalKerningWidth(0), GlobalKerningHeight(0)
{
#ifdef _DEBUG
    setDebugName("ScalableFont");
#endif

    m_fallback_font          = NULL;
    m_fallback_kerning_width = 0;
    m_fallback_font_scale    = 1.0f;
    m_scale                  = 1.0f;
    m_is_hollow_copy         = false;
    m_black_border           = false;
    m_shadow                 = false;
    m_mono_space_digits      = false;
    m_rtl                    = translations->isRTLLanguage();

    if (Environment)
    {
        // don't grab environment, to avoid circular references
        Driver = Environment->getVideoDriver();

        SpriteBank = Environment->addEmptySpriteBank(io::path(filename.c_str()));
        if (SpriteBank)
            SpriteBank->grab();
    }

    if (Driver)
        Driver->grab();

    setInvisibleCharacters ( L" " );

    io::IXMLReader* reader = file_manager->createXMLReader(filename.c_str());
    if (!load( reader ))
    {
        Log::fatal("ScalableFont", "Loading font failed");
    }
    reader->drop();

    assert(Areas.size() > 0);
}


//! destructor
ScalableFont::~ScalableFont()
{
    if (!m_is_hollow_copy)
    {
        if (Driver)     Driver->drop();
        if (SpriteBank) SpriteBank->drop();
    }
}

void ScalableFont::updateRTL()
{
    m_rtl = translations->isRTLLanguage();
}

void ScalableFont::setShadow(const irr::video::SColor &col)
{
    m_shadow = true;
    m_shadow_color = col;
}

void ScalableFont::doReadXmlFile(io::IXMLReader* xml)
{


  FT_Library    library;
  FT_Face       face;
  FT_GlyphSlot  slot;
  vector <short> offset;

  FT_Init_FreeType( &library );
  FT_New_Face( library, "wqy-microhei.ttf", 0, &face );
  FT_Set_Pixel_Sizes(face, 0, 36);

  slot = face->glyph;

   for ( u32 n = 0; n < 2000 ; ++n )
  {
  	 // Retrieve glyph index from character code, skip useless glyph.
    if (n == 0) continue;
    int idx = FT_Get_Char_Index( face, n);
    if (idx == 0)  continue;

    FT_Set_Pixel_Sizes(face, 0, 36);
   // Load glyph image into the slot (erase previous one)
    FT_Load_Glyph( face , idx , FT_LOAD_DEFAULT | FT_LOAD_RENDER | FT_LOAD_TARGET_NORMAL);
    
    // Store offset on horizontal line.
    short offset_on_line = (face->glyph->metrics.height >> 6) - face->glyph->bitmap_top;
    offset.push_back(offset_on_line);
    
    // Convert to an anti-aliased bitmap
	 FT_Bitmap bits = slot->bitmap;

	core::dimension2du d(bits.width + 1, bits.rows + 1);
	core::dimension2du texture_size;

	// Store it as texture.
	video::IImage* image = 0;
	switch (bits.pixel_mode)
	{
		case FT_PIXEL_MODE_MONO:
		{
			// Create a blank image and fill it with transparent pixels.
			texture_size = d.getOptimalSize(true, true);
			image = Driver->createImage(video::ECF_A1R5G5B5, texture_size);
			image->fill(video::SColor(0, 255, 255, 255));

			// Load the monochrome data in.
			const u32 image_pitch = image->getPitch() / sizeof(u16);
			u16* image_data = (u16*)image->lock();
			u8* glyph_data = bits.buffer;
			for (s32 y = 0; y < bits.rows; ++y)
			{
				u16* row = image_data;
				for (s32 x = 0; x < bits.width; ++x)
				{
					// Monochrome bitmaps store 8 pixels per byte.  The left-most pixel is the bit 0x80.
					// So, we go through the data each bit at a time.
					if ((glyph_data[y * bits.pitch + (x / 8)] & (0x80 >> (x % 8))) != 0)
						*row = 0xFFFF;
					++row;
				}
				image_data += image_pitch;
			}
			image->unlock();
			break;
		}

		case FT_PIXEL_MODE_GRAY:
		{
			// Create our blank image.
			texture_size = d.getOptimalSize(!Driver->queryFeature(video::EVDF_TEXTURE_NPOT), !Driver->queryFeature(video::EVDF_TEXTURE_NSQUARE), true, 0);
			image = Driver->createImage(video::ECF_A8R8G8B8, texture_size);
			image->fill(video::SColor(0, 255, 255, 255));

			// Load the grayscale data in.
			const float gray_count = static_cast<float>(bits.num_grays);
			const u32 image_pitch = image->getPitch() / sizeof(u32);
			u32* image_data = (u32*)image->lock();
			u8* glyph_data = bits.buffer;
			for (s32 y = 0; y < bits.rows; ++y)
			{
				u8* row = glyph_data;
				for (s32 x = 0; x < bits.width; ++x)
				{
					image_data[y * image_pitch + x] |= static_cast<u32>(255.0f * (static_cast<float>(*row++) / gray_count)) << 24;
					//data[y * image_pitch + x] |= ((u32)(*bitsdata++) << 24);
				}
				glyph_data += bits.pitch;
			}
			image->unlock();
			break;
		}
		default:
			// TODO: error message?
			break;
	}

	 SpriteBank->addTextureAsSprite(Driver->addTexture("character",image));
	 image->drop();
    CharacterMap[(wchar_t)n] =  SpriteBank->getSprites().size() -1;
}
//Fix unused glyphs....

       CharacterMap[(wchar_t)32] =  1; //I don't know why it has to be set an value to whitespace to make it displayable,
                                       //without this hack space at ignored in stk.
       CharacterMap[(wchar_t)173] = 0; //Don't need a glyph for the soft hypen, as it only print when not having enough space.
                                       //And then it will convert to a "-".
       core::array<core::rect<s32> >& rectangle = SpriteBank->getPositions();

       for (unsigned int n = 0 ; n < SpriteBank->getSprites().size(); ++n)
{//Storing now    
    SFontArea a;
    a.underhang     = 0;
    a.overhang      = 0;
    a.spriteno      = n;
    a.offsety = offset.at(n);
    a.width = rectangle[n].getWidth();
     // add character to font
    Areas.push_back(a);
  }

  FT_Done_Face    ( face );
  FT_Done_FreeType( library );

}



//! loads a font file from xml
bool ScalableFont::load(io::IXMLReader* xml)
{
    if (!SpriteBank)
    {
        Log::error("ScalableFont::load", "SpriteBank is NULL!!");
        return false;
    }

    doReadXmlFile(xml);

    // set bad character
    WrongCharacter = getAreaIDFromCharacter(L' ', NULL);

    setMaxHeight();

    for(wchar_t c='0'; c<='9'; c++)
    {
        SFontArea a = getAreaFromCharacter(c, NULL);
        if(a.overhang  > m_max_digit_area.overhang ) m_max_digit_area.overhang  = a.overhang;
        if(a.underhang > m_max_digit_area.underhang) m_max_digit_area.underhang = a.underhang;
        if(a.width     > m_max_digit_area.width    ) m_max_digit_area.width     = a.width;
    }
    m_max_digit_area.overhang = 0;m_max_digit_area.underhang=0;
    return true;
}
void ScalableFont::setScale(const float scale)
{
    m_scale = scale;
}

void ScalableFont::setMaxHeight()
{
    MaxHeight = 0;
    s32 t;

    core::array< core::rect<s32> >& p  = SpriteBank->getPositions();
    core::array< SGUISprite >& sprites = SpriteBank->getSprites();

    for (u32 i=0; i<p.size(); ++i)
    {
        t = p[i].getHeight();

        // FIXME: consider fallback fonts
        int texID = sprites[i].Frames[0].textureNumber;

        const TextureInfo& info = (*(m_texture_files.find(texID))).second;
        if (info.m_exclude_from_max_height_calculation) continue;

        //float char_scale = info.m_scale;
        float char_scale = 1.0f;
        t = (int)(t*char_scale);

        if (t>MaxHeight)
            MaxHeight = t;
    }

    MaxHeight = (int)(MaxHeight*m_scale);
}



//! set an Pixel Offset on Drawing ( scale position on width )
void ScalableFont::setKerningWidth(s32 kerning)
{
    GlobalKerningWidth = kerning;
}


//! set an Pixel Offset on Drawing ( scale position on width )
s32 ScalableFont::getKerningWidth(const wchar_t* thisLetter, const wchar_t* previousLetter) const
{

    s32 ret = GlobalKerningWidth;

    if (thisLetter)
    {
        ret += Areas[getAreaIDFromCharacter(*thisLetter, NULL)].overhang;

        if (previousLetter)
        {
            ret += Areas[getAreaIDFromCharacter(*previousLetter, NULL)].underhang;
        }
    }

    return ret;
}


//! set an Pixel Offset on Drawing ( scale position on height )
void ScalableFont::setKerningHeight(s32 kerning)
{
    GlobalKerningHeight = kerning;
}


//! set an Pixel Offset on Drawing ( scale position on height )
s32 ScalableFont::getKerningHeight () const
{
    return GlobalKerningHeight;
}


//! returns the sprite number from a given character
u32 ScalableFont::getSpriteNoFromChar(const wchar_t *c) const
{
    return Areas[getAreaIDFromCharacter(*c, NULL)].spriteno;
}


s32 ScalableFont::getAreaIDFromCharacter(const wchar_t c, bool* fallback_font) const
{
    std::map<wchar_t, s32>::const_iterator n = CharacterMap.find(c);
    if (n != CharacterMap.end())
    {
        if (fallback_font != NULL) *fallback_font = false;
        //Log::info("ScalableFont", "Character %d found in font", (int)c);
        return (*n).second;
    }
    else if (m_fallback_font != NULL && fallback_font != NULL)
    {
        //Log::warn("ScalableFont", "Font does not have this character: <%d>, try fallback font", (int)c);
        *fallback_font = true;
        return m_fallback_font->getAreaIDFromCharacter(c, NULL);
    }
    else
    {
        //Log::warn("ScalableFont", "The font does not have this character: <%d>", (int)c);
        if (fallback_font != NULL) *fallback_font = false;
        return WrongCharacter;
    }
}

const ScalableFont::SFontArea &ScalableFont::getAreaFromCharacter(const wchar_t c,
                                                    bool* fallback_font) const
{
    const int area_id = getAreaIDFromCharacter(c, fallback_font);


    if(m_mono_space_digits && ( (c>=L'0' && c<=L'9') || c==L' ' ) )
    {
        const SFontArea &area = (fallback_font && *fallback_font)
                              ? m_fallback_font->Areas[area_id]
                              : Areas[area_id];
        m_max_digit_area.spriteno = area.spriteno;
        return m_max_digit_area;
    }

    const bool use_fallback_font = (fallback_font && *fallback_font);

    if (use_fallback_font)
    {
        assert(area_id < (int)m_fallback_font->Areas.size());
    }
    else
    {
        assert(area_id < (int)Areas.size());
    }

    // Note: fallback_font can be NULL
    return ( use_fallback_font ? m_fallback_font->Areas[area_id] : Areas[area_id]);
}   // getAreaFromCharacter


void ScalableFont::setInvisibleCharacters( const wchar_t *s )
{
    Invisible = s;
}


//! returns the dimension of text
core::dimension2d<u32> ScalableFont::getDimension(const wchar_t* text) const
{
    assert(Areas.size() > 0);

    core::dimension2d<u32> dim(0, 0);
    core::dimension2d<u32> thisLine(0, (int)(MaxHeight*m_scale));

    for (const wchar_t* p = text; *p; ++p)
    {
        if (*p == L'\r'  ||      // Windows breaks
            *p == L'\n'      )   // Unix breaks
        {
            if (*p==L'\r' && p[1] == L'\n') // Windows breaks
                ++p;
            dim.Height += thisLine.Height;
            if (dim.Width < thisLine.Width)
                dim.Width = thisLine.Width;
            thisLine.Width = 0;
            continue;
        }

        bool fallback = false;
        const SFontArea &area = getAreaFromCharacter(*p, &fallback);

        thisLine.Width += area.underhang;

        thisLine.Width += getCharWidth(area, fallback);
    }

    dim.Height += thisLine.Height;
    if (dim.Width < thisLine.Width) dim.Width = thisLine.Width;

   //Log::info("ScalableFont", "ScalableFont::getDimension returns: %d, %d", dim.Width, dim.Height);

    dim.Width  = (int)(dim.Width + 0.9f); // round up
    dim.Height = (int)(dim.Height + 0.9f);

    //Log::info("ScalableFont", "After: %d, %d", dim.Width, dim.Height);

    return dim;
}

void ScalableFont::draw(const core::stringw& text,
    const core::rect<s32>& position, video::SColor color,
    bool hcenter, bool vcenter,
    const core::rect<s32>* clip)
{
    doDraw(text, position, color, hcenter, vcenter, clip, NULL);
}

void ScalableFont::draw(const core::stringw& text,
                        const core::rect<s32>& position, video::SColor color,
                        bool hcenter, bool vcenter,
                        const core::rect<s32>* clip, bool ignoreRTL)
{
    bool previousRTL = m_rtl;
    if (ignoreRTL) m_rtl = false;

    doDraw(text, position, color, hcenter, vcenter, clip, NULL);

    if (ignoreRTL) m_rtl = previousRTL;
}

//! draws some text and clips it to the specified rectangle if wanted
void ScalableFont::doDraw(const core::stringw& text,
                          const core::rect<s32>& position, video::SColor color,
                          bool hcenter, bool vcenter,
                          const core::rect<s32>* clip,
                          FontCharCollector* charCollector)
{
    if (!Driver) return;

    if (m_shadow)
    {
        m_shadow = false; // avoid infinite recursion

        core::rect<s32> shadowpos = position;
        shadowpos.LowerRightCorner.X += 2;
        shadowpos.LowerRightCorner.Y += 2;

        draw(text, shadowpos, m_shadow_color, hcenter, vcenter, clip);

        m_shadow = true; // set back
    }

    core::position2d<s32> offset = position.UpperLeftCorner;
    core::dimension2d<s32> text_dimension;

    if (m_rtl || hcenter || vcenter || clip)
    {
        text_dimension = getDimension(text.c_str());

        if (hcenter)    offset.X += (position.getWidth() - text_dimension.Width) / 2;
        else if (m_rtl) offset.X += (position.getWidth() - text_dimension.Width);

        if (vcenter)    offset.Y += (position.getHeight() - text_dimension.Height) / 2;
        if (clip)
        {
            core::rect<s32> clippedRect(offset, text_dimension);
            clippedRect.clipAgainst(*clip);
            if (!clippedRect.isValid()) return;
        }
    }

    // ---- collect character locations
    const unsigned int text_size = text.size();
    core::array<s32>               indices(text_size);
    core::array<core::position2di> offsets(text_size);
    std::vector<bool>              fallback(text_size);
    for (u32 i = 0; i<text_size; i++)
    {
        wchar_t c = text[i];

        if (c == L'\r' ||          // Windows breaks
            c == L'\n'    )        // Unix breaks
        {
            if(c==L'\r' && text[i+1]==L'\n') c = text[++i];
            offset.Y += (int)(MaxHeight*m_scale);
            offset.X  = position.UpperLeftCorner.X;
            if (hcenter)
                offset.X += (position.getWidth() - text_dimension.Width) >> 1;
            continue;
        }   // if lineBreak

        bool use_fallback_font = false;
        const SFontArea &area  = getAreaFromCharacter(c, &use_fallback_font);
        fallback[i]            = use_fallback_font;
        offset.X              += area.underhang;
        int padding = (int)((float) area.offsety*m_scale);
        offset.Y += padding; 
        offsets.push_back(offset);
        offset.Y -= padding;
        // Invisible character. add something to the array anyway so that
        // indices from the various arrays remain in sync
        indices.push_back( Invisible.findFirst(c) < 0  ? area.spriteno
                                                       : -1            );
        offset.X += getCharWidth(area, fallback[i]);
    }   // for i<text_size

    // ---- do the actual rendering
    const int indiceAmount                    = indices.size();
    core::array< SGUISprite >& sprites        = SpriteBank->getSprites();
    core::array< core::rect<s32> >& positions = SpriteBank->getPositions();
    core::array< SGUISprite >* fallback_sprites;
    core::array< core::rect<s32> >* fallback_positions;
    if(m_fallback_font!=NULL)
    {
        fallback_sprites   = &m_fallback_font->SpriteBank->getSprites();
        fallback_positions = &m_fallback_font->SpriteBank->getPositions();
    }
    else
    {
        fallback_sprites   = NULL;
        fallback_positions = NULL;
    }

    const int spriteAmount      = sprites.size();
    for (int n=0; n<indiceAmount; n++)
    {
        const int spriteID = indices[n];
        if (!fallback[n] && (spriteID < 0 || spriteID >= spriteAmount)) continue;
        if (indices[n] == -1) continue;

        //assert(sprites[spriteID].Frames.size() > 0);

        const int texID = (fallback[n] ?
                           (*fallback_sprites)[spriteID].Frames[0].textureNumber :
                           sprites[spriteID].Frames[0].textureNumber);

        core::rect<s32> source = (fallback[n] ?
                                  (*fallback_positions)[(*fallback_sprites)[spriteID].Frames[0].rectNumber] :
                                  positions[sprites[spriteID].Frames[0].rectNumber]);

        //const TextureInfo& info = (fallback[n] ?
        //                           (*(m_fallback_font->m_texture_files.find(texID))).second :
        //                           (*(m_texture_files.find(texID))).second
        //                           );
        //float char_scale = info.m_scale;
        float char_scale = 1.0f;
        core::dimension2d<s32> size = source.getSize();

        float scale = (fallback[n] ? m_scale*m_fallback_font_scale : m_scale);
        size.Width  = (int)(size.Width  * scale * char_scale);
        size.Height = (int)(size.Height * scale * char_scale);

        // align vertically if character is smaller
        //int y_shift = (size.Height < MaxHeight*m_scale ? (int)((MaxHeight*m_scale - size.Height)/2.0f) : 0);
        int y_shift =(int) ((MaxHeight- source.getHeight() -5)*m_scale); //Make bitmap ttf font with their lower position render just above the drawing line
                                                                          //Then apply the padding offset required. -5 to make it more vertically central.
        //core::rect<s32> dest(offsets[n] + core::position2di(0, y_shift), size);
        core::rect<s32> dest(offsets[n] + core::position2di(0, y_shift), size);

        video::ITexture* texture = (fallback[n] ?
                                    m_fallback_font->SpriteBank->getTexture(texID) :
                                    SpriteBank->getTexture(texID) );

        /*
        if (fallback[n])
        {
            Log::info("ScalableFont", "Using fallback font %s; source area is %d, %d; size %d, %d; dest = %d, %d",
                core::stringc(texture->getName()).c_str(), source.UpperLeftCorner.X, source.UpperLeftCorner.Y,
                source.getWidth(), source.getHeight(), offsets[n].X, offsets[n].Y);
        }
        */
        //GL32_draw2DRectangle(video::SColor(255, 255,0,0), dest,clip);
        if (texture == NULL)
        {
            // perform lazy loading

            if (fallback[n])
            {
                m_fallback_font->lazyLoadTexture(texID);
                texture = m_fallback_font->SpriteBank->getTexture(texID);
            }
            else
            {
                lazyLoadTexture(texID);
                texture = SpriteBank->getTexture(texID);
            }

            if (texture == NULL)
            {
                Log::warn("ScalableFont", "Character not found in current font");
                continue; // no such character
            }
        }

        if (m_black_border && charCollector == NULL)
        {
            // draw black border
            video::SColor black(color.getAlpha(),0,0,0);

            for (int x_delta=-2; x_delta<=2; x_delta++)
            {
                for (int y_delta=-2; y_delta<=2; y_delta++)
                {
                    if (x_delta == 0 || y_delta == 0) continue;
                    draw2DImage(texture,
                                dest + core::position2d<s32>(x_delta, y_delta),
                                source,
                                clip,
                                black, true);
                }
            }
        }

        if (fallback[n])
        {
            // TODO: don't hardcode colors?
            video::SColor orange(color.getAlpha(), 255, 100, 0);
            video::SColor yellow(color.getAlpha(), 255, 220, 15);
            video::SColor title_colors[] = {orange, yellow, orange, yellow};

            if (charCollector != NULL)
            {
                charCollector->collectChar(texture,
                    dest,
                    source,
                    title_colors);
            }
            else
            {
                draw2DImage(texture,
                    dest,
                    source,
                    clip,
                    title_colors, true);
            }
        }
        else
        {
            if (charCollector != NULL)
            {
                video::SColor colors[] = { color, color, color, color };
                charCollector->collectChar(texture,
                    dest,
                    source,
                    colors);
            }
            else
            {
                draw2DImage(texture,
                    dest,
                    source,
                    clip,
                    color, true);
            }
//#ifdef FONT_DEBUG
#if 1
          /*  video::IVideoDriver* driver = GUIEngine::getDriver();
            driver->draw2DLine(core::position2d<s32>(dest.UpperLeftCorner.X,  dest.UpperLeftCorner.Y),
                               core::position2d<s32>(dest.UpperLeftCorner.X,  dest.LowerRightCorner.Y),
                               video::SColor(255, 255,0,0));
            driver->draw2DLine(core::position2d<s32>(dest.LowerRightCorner.X, dest.LowerRightCorner.Y),
                               core::position2d<s32>(dest.LowerRightCorner.X, dest.UpperLeftCorner.Y),
                               video::SColor(255, 255,0,0));
            driver->draw2DLine(core::position2d<s32>(dest.LowerRightCorner.X, dest.LowerRightCorner.Y),
                               core::position2d<s32>(dest.UpperLeftCorner.X,  dest.LowerRightCorner.Y),
                               video::SColor(255, 255,0,0));
            driver->draw2DLine(core::position2d<s32>(dest.UpperLeftCorner.X,  dest.UpperLeftCorner.Y),
                               core::position2d<s32>(dest.LowerRightCorner.X, dest.UpperLeftCorner.Y),
                               video::SColor(255, 255,0,0));*/
                              
#endif
        }
    }
}


void ScalableFont::lazyLoadTexture(int texID)
{
/*    Driver->setTextureCreationFlag(video::ETCF_CREATE_MIP_MAPS, true);

    // load texture
    //assert(m_texture_files[texID].m_file_name.size() > 0);

    // Font textures can not be resized (besides the impact on quality in
    // this case, the indices in the xml files would become wrong).
    core::dimension2du old_max_size = Driver->getDriverAttributes()
                                     .getAttributeAsDimension2d("MAX_TEXTURE_SIZE");
    Driver->getNonConstDriverAttributes().setAttribute("MAX_TEXTURE_SIZE",
                                                       core::dimension2du(0, 0));

    SpriteBank->setTexture(texID, Driver->getTexture( m_texture_files[texID].m_file_name ));
    Driver->getNonConstDriverAttributes().setAttribute("MAX_TEXTURE_SIZE", old_max_size);

    // set previous mip-map+filter state
    //Driver->setTextureCreationFlag(video::ETCF_CREATE_MIP_MAPS, mipmap);

    // couldn't load texture, abort.
    if (!SpriteBank->getTexture(texID))
    {
        Log::error("ScalableFont::lazyLoadTexture", "Unable to load all textures in the font");
        _IRR_IMPLEMENT_MANAGED_MARSHALLING_BUGFIX;
        return;
    }
    else
    {
        assert(m_texture_files[texID].m_file_name.size() > 0);

        // colorkey texture rather than alpha channel?
        if (! m_texture_files[texID].m_has_alpha)
        {
            Driver->makeColorKeyTexture(SpriteBank->getTexture(texID), core::position2di(0,0));
        }
    }*/
}

int ScalableFont::getCharWidth(const SFontArea& area, const bool fallback) const
{
    core::array< SGUISprite >& sprites = SpriteBank->getSprites();
    core::array< SGUISprite >* fallback_sprites = (m_fallback_font != NULL ?
                                                   &m_fallback_font->SpriteBank->getSprites() :
                                                   NULL);

    const int texID = (fallback ?
                       (*fallback_sprites)[area.spriteno].Frames[0].textureNumber :
                       sprites[area.spriteno].Frames[0].textureNumber);

    const TextureInfo& info = (fallback ?
                               (*(m_fallback_font->m_texture_files.find(texID))).second :
                                (*(m_texture_files.find(texID))).second
                               );
    assert(info.m_file_name.size() > 0);
    //const float char_scale = info.m_ + ' ', scale;
    const float char_scale = 1.0f;

    //Log::info("ScalableFont", "area.spriteno = %d, char_scale = %f", area.spriteno, char_scale);

    if (fallback) return (int)(((area.width + area.overhang)*m_fallback_font_scale + m_fallback_kerning_width) * m_scale * char_scale);
    else          return (int)((area.width + area.overhang + GlobalKerningWidth) * m_scale * char_scale);
}


//! Calculates the index of the character in the text which is on a specific position.
s32 ScalableFont::getCharacterFromPos(const wchar_t* text, s32 pixel_x) const
{
    s32 x = 0;
    s32 idx = 0;

    while (text[idx])
    {
        bool use_fallback_font = false;
        const SFontArea &a  = getAreaFromCharacter(text[idx], &use_fallback_font);

        x += getCharWidth(a, use_fallback_font) + a.overhang + a.underhang + GlobalKerningWidth;

        if (x >= pixel_x)
            return idx;

        ++idx;
    }

    return -1;
}


IGUISpriteBank* ScalableFont::getSpriteBank() const
{
    return SpriteBank;
}

} // end namespace gui
} // end namespace irr


```

And them to cmakelist
```
# Freetype
find_package(Freetype REQUIRED)
include_directories(${FREETYPE_INCLUDE_DIRS})
...

target_link_libraries(supertuxkart
....
   ${OPENGL_LIBRARIES}
  ${FREETYPE_LIBRARIES}
```
And in scalable_font.hpp
add:
```
#include <ft2build.h>
#include FT_FREETYPE_H
```
and short   offsety;   in struct SFontArea

There should be a disable in engine.cpp about title ,digit  and fallback font. Do sth like g_digit_font = sfont.


Comment welcome..
-----------------

**Comment by konstin** [comment]
I really like the work you're doing, but please put large code pieces into [gists](https://gist.github.com) to improve readbility

**Comment by auriamg** [comment]
Agreed, or just commit in a branch in your clone and point us to the commits :) would be much easier to review and also to test it

**Comment by hiker** [comment]
+1

I should have a computer to work on soonish.

Just one comment: I find the text in the screenshot "This is how on 1920x1080, less mis-align." (from the help screen) very difficult to read - there seems to be not enough space between the words (imho). Is this an issue with the font?

**Comment by Benau** [comment]
Just one comment: I find the text in the screenshot "This is how on 1920x1080, less mis-align." (from the help screen) very difficult to read - there seems to be not enough space between the words (imho). Is this an issue with the font?
-----------------------
Now it's fixed(mostly)

![2015-09-17 15-41-39](https://cloud.githubusercontent.com/assets/3252341/9927599/a292219a-5d52-11e5-8539-220f75fa398c.png)

I will make a new branch after I finished writing a function to load char base on current language.

**Comment by Benau** [comment]
Now freetype branch is located here:
https://github.com/Benau/stk-code/tree/freetype

freetypetesting will stay sometimes for reference rendering.

To test copy wqy-microhei.ttf (or other fonts for Arabic or Hebrew) and rename to current building directory. I think char shouldn't disappear unless the fonts themselves don't contain that glyph. Otherwise there're something wrong with the writeallchar function in tinygettext, please tell me if so....

To change languages you have to use suitable fonts and restart stk currently, use change resolution as a quick hack.

The license of fonts should be ok to include in stk, wqy itself used by stk as bitmap font. 

And arabic and hebrew source (both from arch pkg):

https://aur.archlinux.org/packages/ttf-amiri/
https://aur.archlinux.org/packages/culmus/

I want to know why the fallback fonts don't appear................. I can't figure it out on my own, help me.....

That has to be fixed before making more progress.
Reference result:

![2015-09-18 20-45-07](https://cloud.githubusercontent.com/assets/3252341/9959953/324a9b26-5e4a-11e5-8a10-653833eadf35.png)
![2015-09-18 20-53-15](https://cloud.githubusercontent.com/assets/3252341/9959955/343fd522-5e4a-11e5-8d0a-e096ab5ad038.png)

Say goodbye to blurred bitmap fonts......

**Comment by Benau** [comment]
UPDATE!!
b652c683231132cc3b77e3c3927f0e1101c16b71
Loading ttf file base on stk file manager is implemented now, so to test just check out my freetype branch, and then compile and run. No more addition hacking is needed.

Comment welcome, esp the TTFfile.cpp, I don't know a lot about c++ class so I used a struct instead.....

**Comment by Benau** [comment]
*To get fallback font to display, seems that I need to load all font using freetype..

**Comment by Benau** [comment]
UPDATE!!!
*I squash old commits into one for a easier view
https://github.com/Benau/stk-code/commit/9f06f7053615f2cf9e98cc5f875d9182f97e45e2

Thank @hiker for idea to enable instant changing language, now stk-freetype can do that now, do u think I implemented that correctly?

I add 3 fonts to test, 2 of them are languages that old stk doesn't include their fonts to display
![2015-09-23 03-40-50](https://cloud.githubusercontent.com/assets/3252341/10029562/26ef2f7c-61a5-11e5-8a45-7869a90dd099.png)

I add the original english fonts as a easy comparison to old stk too:

![2015-09-22 02-00-50](https://cloud.githubusercontent.com/assets/3252341/10029582/4ac8f61c-61a5-11e5-81b5-ed49a5a13613.png)

They are fetched from debian and mandriva pkg database and I make sure that their licence is ok to redistribute

**Comment by Benau** [comment]
https://github.com/Benau/stk-code/commit/7f5069589618436811c6f3676ba1e8f000719f9b

Final task (hopefully), billboard text

![2015-09-23 16-35-02](https://cloud.githubusercontent.com/assets/3252341/10040781/4dd8a3b8-6211-11e5-8e27-41fb13f6a050.png)
As you can see, I think stk got the texture for leader already which has 6 box for 6 chars in "leader", but sth wrong with color?

Have you got any idea to fix billboard text?

Where should I hack in stk_text_billboard.cpp? (or is it the suitable file?)

**Comment by auriamg** [comment]
Nice progress :) we should definitely take a look at this after the release.

Also, I tried it on Windows. Needed to apply this fix to the build system to make it build, maybe you can consider adding that?

```
From 21ff56756595811ca39ff1dbd61654cbdf61babd Mon Sep 17 00:00:00 2001
From: Marianne Gagnon <auria.mg@gmail.com>
Date: Wed, 23 Sep 2015 19:05:55 -0400
Subject: [PATCH] Freetype build on windows

---
 CMakeLists.txt           | 1 +
 cmake/FindFreetype.cmake | 5 +++++
 2 files changed, 6 insertions(+)
 create mode 100644 cmake/FindFreetype.cmake

diff --git a/CMakeLists.txt b/CMakeLists.txt
index a2b5260..b7fa738 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -351,6 +351,7 @@ target_link_libraries(supertuxkart
     ${OGGVORBIS_LIBRARIES}
     ${OPENAL_LIBRARY}
     ${OPENGL_LIBRARIES}
+    ${FREETPYE_LIBRARIES}
     )
 
 if(UNIX AND NOT APPLE)
diff --git a/cmake/FindFreetype.cmake b/cmake/FindFreetype.cmake
new file mode 100644
index 0000000..7d5ebe5
--- /dev/null
+++ b/cmake/FindFreetype.cmake
@@ -0,0 +1,5 @@
+
+find_path(FREETYPE_INCLUDE_DIRS NAMES freetype/freetype.h PATHS "${PROJECT_SOURCE_DIR}/dependencies/include")
+find_library(FREETPYE_LIBRARY NAMES freetype PATHS "${PROJECT_SOURCE_DIR}/dependencies/lib")
+set(FREETYPE_FOUND 1)
+set(FREETPYE_LIBRARIES ${FREETPYE_LIBRARY})
-- 
1.8.3.msysgit.0
```

Regarding billboard text, you are looking at the right place. What it does is trigger a pseudo-render of the font - but instead of actually rendering the letters, it simply collects a list of textures and positions, and then creates a mesh out of that info (one quad per character)

And not sure what you mean about uppercase?

**Comment by Benau** [comment]
https://github.com/Benau/stk-code/commit/2f896808fcc80fb65eb9d2610a7bfb1673573d52
Should work and build now I hope.

![default](https://cloud.githubusercontent.com/assets/3252341/10086432/f670b594-6340-11e5-81da-bdcd2af9b97c.png)

Tested on win 8 of vs 2013. I can run without this commit on linux/msys on win vista, maybe gcc /linux are more tolerated to error, Anyway...

Regarding performance, freetype stk gain ~8MB memory usage, but both version of game play can obtain max fps. Also when keep changing of language in freetype stk increase ram usage every time (~2MB per change, more for ZH/JP/KR). I can't figure out how to deal with it atm, but should be unlikely for a normal user to do so.

---------

I meant do you think SUPERTUXKART is better than Supertuxkart in the title for loading less char texture (like screenshot above)? (I assume you like as in the commit)

I add function of info about glyphs loaded with should give some ideas...

----------

BTW you should tell people to use vs2013 for "Windows Desktop" instead of "Windows" in README as the later one refuse to build stk, M$ really sucks to sell useless programs.....

**Comment by deveee** [comment]
I didn't check last commits (I'm out of home), but I fixed vs2015
compilation some time ago. If you have a problem with this, please
open a ticket.

**Comment by auriamg** [comment]
Nice progress, though I still get a crash. The reason is that you can't erase from an operator while iterating the way you're doing it.

This :
```
    std::set<wchar_t>::iterator it;
    for (it=ttf_file->usedchar.begin(); it!=ttf_file->usedchar.end(); ++it)
    {
        if (iswlower((wchar_t)*it) || *it == (wchar_t)105) //Don't know why "i" get unremoved.
            ttf_file->usedchar.erase(it);
    }
```

Should be like this :
```
    std::set<wchar_t>::iterator it = ttf_file->usedchar.begin();
    while (it != ttf_file->usedchar.end())
    {
        if (iswlower((wchar_t)*it) || *it == (wchar_t)105) //Don't know why "i" get unremoved.
        {
            it = ttf_file->usedchar.erase(it);
        }
        else
        {
            ++it;
        }
    }
```

Apart from that it's coming along pretty well :) The Font is a bit too big and minor stuff like that but that's very minor at this point

**Comment by Benau** [comment]
https://github.com/Benau/stk-code/commit/a90e4a8ba4969519a9258d62e0e76af60cd4f7a1

Good code?

**Comment by konstin** [comment]
Except for what I noted the code looks fine.

**Comment by deveee** [comment]
Tbh. I would prefer not to use non-typical libraries such as harfbuzz if 
it's not necessary. It means more work for creating packages. You can't 
be sure that it will work on every architecture with every compiler, 
including cross-compilation, 64-bit windows compilation in future etc.

**Comment by Benau** [comment]
as developers said in irc, we should use a font that contains characters for most languages, so the 
else if  *** stuff shall get removed when the final font is picked

**Comment by Benau** [comment]
https://github.com/Benau/stk-code/commit/c45289428bc3a4fe575101d1857b43ece8a7f6d0

Should fix the "The Font is a bit too big" issue?

**Comment by Benau** [comment]
see #2320 for harfbuzz-related update

**Comment by cap44** [comment]
@Benau Hebrew looks fine in my opinion, I can't comment on Arabic, unfortunately

**Comment by Benau** [comment]
*squashed old commits into one for a easier view, also merged master change
https://github.com/Benau/stk-code/commit/928af28573ea0645d680c3ea9b0a980aeb1e166c

After finished dealing the arabic issue, I think I can move on to the billboard text again (hopefully)............

See #2320 for arabic specific update

**Comment by Benau** [comment]
https://github.com/Benau/stk-code/commit/1e7e895d7ffaa05ae03fb7132d0764347b22616b

Finally a ready-to-play freetype stk is available!

First of all thanks @auriamg for quick billboard text fix.

Although it has a bug unrelated to freetype display, which the bubblegum left on the ground has no texture :(, the material.cpp may need more fix...

Regarding the offset on Y, now I have to set 2 of them to deal with normal and billboard text. If you don't understand what they mean, take the following screenshots for example:

This is how stk draw2dimage without any offset
![1](https://cloud.githubusercontent.com/assets/3252341/10128081/eb63d982-65df-11e5-83ed-9d8989565ae5.png)

This is how stk draw billboard text with/o offset
![test](https://cloud.githubusercontent.com/assets/3252341/10303534/01193980-6c47-11e5-876a-9be3e86d20db.jpg)

As you can see, normal text is drawn top-down while billboard is bottom-up, if we can make stk draw all text (texture) bottom-up, only 1 offsety is needed. (but minus sign is required for billboard text, don't know why)

-----------------------------
After basic implementation, there're some further fixes I can think of:

1.Load by Glyph pages as @auriamg suggested
But it's a bit complicate for me to code, I need some help for that............

2.Change title font color according to skin (important and easy?)
As they are color-able now, it would be good to make them match the skin.

3.(Optional??)Configurable font for experts?
Allowing overwritten the default font config, ie custom font, can be done on command line side.

If 2+3 are done, this will make stk look like this:

![2015-10-06 15-41-10](https://cloud.githubusercontent.com/assets/3252341/10303703/1cc2f4a4-6c48-11e5-880e-3a2055882c1c.png)

We can considering adding more skin after that, like "Ruby" for red gui for skin and fonts. "Forest" for green....

Thanks @SafaAlfulaij too for the test on his old opengl driver pc and arabic comments, he said it's playable.

**Comment by Benau** [comment]
Turns out that I should be able to implement loading by glyph pages by myself, I will push to git after I finished.

**Comment by Benau** [comment]
Benau@ebeca35460

Now basic glyph page loading is done, some less than perfect thing is that after changing resolution, edges come out from the rectangle of text, but after a complete restart they will gone.

Maybe the createNewGlyphPage is to blame? Is there a better way which can create a blank texture and discard the old one? Currently i overwrite the old texture with a blank one.

The no. of resulting glyph pages are screen resolution dependent, so it can  make stk to load fewer texture as in #2316. You can actually know how many glyph and page are loaded as in log.

Any comments about the code?

**Comment by Benau** [comment]
https://github.com/Benau/stk-code/commit/486495d976cec53b480f6a7d1710ab4656e1dfd6

Tested on win32

Now all freetype related file are written in c++ class, which enable better coding style with current stk

Windows build tested, the edge showing issue doesn't happen on Windows by the way (quick test).
Maybe driver problems?

This is what looks like on linux:

![default](https://cloud.githubusercontent.com/assets/3252341/10375396/db58a042-6e2a-11e5-944d-6ec9287b4767.png)

**Comment by Benau** [comment]
https://github.com/Benau/stk-code/commit/a7b2c8838fffb10a144c64518a6470fcc21dad2c

NOT tested on windows

I preload more title font for testing propose, current it need 4 pages of glyph to display up to latin-B utf code range on 1920x1080, Do you think we need more or less?

I add a dumpGlyphPage function so you can actually see what words are added easily. (and space left).

**Comment by Benau** [comment]
https://github.com/Benau/stk-code/commit/a756f9f90e0d0406cdcf85e017984ffe56936f9a

Better title font to all language.

*Note: It will automatically sort out unsupported char (like CJK,arabic which is resource-wasting to create a title font) by a switch in scalable_font (if (idx)). So if current bold font (FreeSansBold) doesn't have the glyph to that used char, it will skip.

I tested all lanuages, all of them require only 2 glyph pages on 1920x1080 resolution.

The space hack should enable users to use no matter what ttf files they want to choose (fonts without non-breaking space).

Since freetype should be stable now, I sort out some issues here regarding fonts, most of them will get a auto fix after freetype is ready:
#2140, #1814, #1789, #1736, #1370, #1173, #956, #89 
I will post screenshot of current chars look like there

regarding #2112, as ft_environment and glyphpagecreator stays with guiengine now, we should be able to create needed chars "on the fly", is it worth to support cjk input?

**Comment by Benau** [comment]
https://github.com/Benau/stk-code/commit/1856e8e20ea5422b18d79d19aaa55b7669de19a8

I created a new branch to allow easy compare, on my slow pc, it takes 1 second less to show the loading screen when using chinese on lazyloadchar branch.
 
To prevent mismatching, I remove Layne Hansom font there. Now stk can display no matter what char regardless of current language and used characters in stk.

![2015-10-17 02-45-30](https://cloud.githubusercontent.com/assets/3252341/10550364/268d991a-7479-11e5-90ee-bd877eddbef0.png)
BTW, there's bug which stk don't update translation of "Laps:" when changing language, need another ticket?

I hack CGUIEditBox.cpp to convert utf8 to utf16 so you can paste chinese into stk (tested in linux), but that failed on windows, it said something like "invaild utf8", anyone know how to fix it (or strictly required)?

**Comment by deveee** [comment]
It's a minor thing, but FindFreetype.cmake file is written poorly. It should be more generic and certainly shouldn't contain ${PROJECT_SOURCE_DIR}/dependencies/lib path. This path is already defined in main cmake file. Tbh. I suppose that FindFreetype already exists in cmake and we don't need this file at all. But as I said, it's a minor thing. It works as it is.

**Comment by auriamg** [comment]
@deveee : on Unix I agree we should be generic, though on OSX/Windows we have an official dependencies pack so no matter what we do we need to make sure the dependency pack is used. I agree the hardcoding is a little hackish but it at least makes sure the build process is easy and painless for OSX/Win users

**Comment by auriamg** [comment]
The freetype branch has been merged into STK master, congratulations @Benau  :)
