### ISSUE TITLE
Zen Garden sometimes does not register laps

### ISSUE THREAD

**Issue by Wuzzy2** [supertuxkart/stk-code#3827]
If you drive the Zen Garden track, sometimes you can drive a round but the game does not register it, forcing you to drive another full round. Once I had to drive full 6 laps in a 4 lap race.

The only shortcut I used was through the trees in front of the bridge. I drove the rest of the track normally.

Tested in version 0.10-rc1.

This is a regression, Zen Garden always worked perfectly in previous versions.

**Comment by auriamg** [comment]
I have modified the track in stk-assets to make the checklines harder to miss. If you are building stk from source, could you try with the latest version of assets and confirm if it's fixed for you?

**Comment by AndetSTK** [comment]
To add onto this, the shortcut in the cave no longer counts the lap.

**Comment by Wuzzy2** [comment]
Meh. The laps still sometimes do not register.

But I noticed a problem at the finish gate. When I go into the finish gate, not perfectly on the road, but on the grass instead, I do not immediately finish. The lap registers a few meters behind. When I drive another round, but perfectly on-road this time, the lap does NOT register.

So maybe the finish gate is the root of all evil! Does the finish checkline (or however you call it) maybe not cover the entire finish gate?

> To add onto this, the shortcut in the cave no longer counts the lap as well.

If it was intented to make the shortcut “illegal”, then the path should be blocked off with stones or something else. Otherwise, the checklines should be fixed, I guess.

**Comment by auriamg** [comment]
Please share a recording or ghost race of when it doesn't register so that we can understand what is happening. Or run stk with flag --check-debug and try to figure out yourself which checkline is being missed

**Comment by auriamg** [comment]
You are right about missing the lap line, good catch : the game detects you crossed the lapline, but doesn't activate the first checkline

**Comment by auriamg** [comment]
I've committed a fix to svn-assets, hopefully it's all fixed by now! Thanks for identifying the root of the problem

**Comment by AndetSTK** [comment]
Hi,
The shortcut in the cave still doesn't work because of a checkline. I just want to make sure that hasn't been forgotten about.

Also, not as big a problem, but the checkline at the bridge makes this shortcut (https://youtu.be/txT_9QLy8es?t=65) and this alternate route (https://youtu.be/txT_9QLy8es?t=74) not work. The shortcut is unintentional so it's not really a problem if it counts the lap, but the alternate route should count.

Thanks!

**Comment by Benau** [comment]
Are u complaining git stk-code (and svn up stk-assets) yourself?

**Comment by AndetSTK** [comment]
I am downloading the track from the media repository assets.

**Comment by auriamg** [comment]
@AndetSTK can you clarify which shortcut using a screenshot? if you mean driving over the pond, that's not actually really an intended driving path

**Comment by AndetSTK** [comment]
![zengarden-2019 04 11_21 09 12](https://user-images.githubusercontent.com/47551843/56005448-60cac380-5c9e-11e9-9064-17c9d2533703.png)
![zengarden-2019 04 11_21 09 30](https://user-images.githubusercontent.com/47551843/56005449-60cac380-5c9e-11e9-9947-12be71624b5d.png)
![zengarden-2019 04 11_21 09 40](https://user-images.githubusercontent.com/47551843/56005433-47297c00-5c9e-11e9-86c4-11eb1bf106a0.png)

The shortcut in the first picture not counting is the main problem.

And as a separate problem, the checkpoint at the bridge makes the pond shortcut (2nd pic) and the alternate route not count (3rd pic). The pond shortcut doesn't need to count since it's unintentional (although it barely saves any time anyway, so personally I think it should count), but the alternate route in the 3rd pic should count the lap.

**Comment by auriamg** [comment]
@AndetSTK I have just removed the way from your first screenshot. This alternative path was never polished properly and has terrible drivability, so for now best remove it as it causes more harm than good. Maybe in the future it can be added back better.

As for your other two screenshots, I have no idea how you manage to use them. I am unable to cross-river without triggering an auto-rescue, and the little cave in your third screenshot leads to a dead end

**Comment by AndetSTK** [comment]
@auriamg Thanks! Yes, I agree it was an awkward shortcut and I'm fine with it being removed entirely at least for now.

For the alternate path, it's possible to get over the fence so that it's not a dead end, but maybe that wasn't intended.

It's weird that you are getting auto-rescued, though. As long as you get enough speed to jump over the river (as opposed to driving through the water), you shouldn't get rescued.

Anyway, I think it's good as it is now.
