### ISSUE TITLE
Not fullscreen

### ISSUE THREAD

**Issue by wb9688** [supertuxkart/stk-code#4037]
## Description

I have both a 1440p and a 1080p monitor connected to my PC. I'm using Wayland with Sway as compositor. SuperTuxKart shows 1440p as option, but when I apply it, it just uses 1080p and I get black bars around it. When I disable my 1080p monitor and apply it, it is able to do 1440p though. I don't have this issue when using X with Openbox.

## Configuration

STK release version: 96fb6f057a4a460ef62cfd2a61199503192e16ff

STK Source (PPA, distribution package, official binary, etc.): Git

System: Debian Unstable

Graphics card: Vega 56

CPU: Ryzen 7 3700X

## Additional information
stdout.log:
```
[info   ] [FileManager]: Data files will be fetched from: 'data/'
[info   ] [FileManager]: Data files will be fetched from: 'data/../../stk-assets/'
[info   ] [FileManager]: User directory is '/home/woutjuh/.config/supertuxkart/config-0.10/'.
[info   ] [FileManager]: Addons files will be stored in '/home/woutjuh/.local/share/supertuxkart/addons/'.
[info   ] [FileManager]: Screenshots will be stored in '/home/woutjuh/.local/share/supertuxkart/screenshots/'.
[info   ] [FileManager]: User-defined grand prix will be stored in '/home/woutjuh/.local/share/supertuxkart/grandprix/'.
[info   ] [FileManager]: Asset 0 will be loaded from 'data/challenges/'.
[info   ] [FileManager]: Asset 1 will be loaded from 'data/gfx/'.
[info   ] [FileManager]: Asset 2 will be loaded from 'data/grandprix/'.
[info   ] [FileManager]: Asset 3 will be loaded from 'data/gui/icons/'.
[info   ] [FileManager]: Asset 4 will be loaded from 'data/gui/screens/'.
[info   ] [FileManager]: Asset 5 will be loaded from 'data/gui/dialogs/'.
[info   ] [FileManager]: Asset 6 will be loaded from 'data/replay/'.
[info   ] [FileManager]: Asset 7 will be loaded from 'data/shaders/'.
[info   ] [FileManager]: Asset 8 will be loaded from 'data/skins/'.
[info   ] [FileManager]: Asset 9 will be loaded from 'data/ttf/'.
[info   ] [FileManager]: Asset 10 will be loaded from 'data/po/'.
[info   ] [FileManager]: Asset 11 will be loaded from 'data/../../stk-assets/library/'.
[info   ] [FileManager]: Asset 12 will be loaded from 'data/../../stk-assets/models/'.
[info   ] [FileManager]: Asset 13 will be loaded from 'data/../../stk-assets/music/'.
[info   ] [FileManager]: Asset 14 will be loaded from 'data/../../stk-assets/sfx/'.
[info   ] [FileManager]: Asset 15 will be loaded from 'data/../../stk-assets/textures/'.
[info   ] [FileManager]: Asset 16 will be loaded from 'data/../../stk-assets/tracks/'.
[verbose  ] translation: Env var LANGUAGE = 'en_US:en'.
[verbose  ] translation: Language 'English (United States)'.
[info   ] tinygettext: Adding language fallback en

[info   ] IrrDriver: OpenGL version: 4.5
[info   ] IrrDriver: OpenGL vendor: X.Org
[info   ] IrrDriver: OpenGL renderer: Radeon RX Vega (VEGA10, DRM 3.27.0, 4.19.0-5-amd64, LLVM 8.0.1)
[info   ] IrrDriver: OpenGL version string: 4.5 (Core Profile) Mesa 19.1.2
[info   ] GLEW: Glew couldn't open glx display.
[info   ] GLDriver: ARB Buffer Storage Present
[info   ] GLDriver: ARB Compute Shader Present
[info   ] GLDriver: ARB Arrays of Arrays Present
[info   ] GLDriver: ARB Texture Storage Present
[info   ] GLDriver: ARB Texture View Present
[info   ] GLDriver: ARB Image Load Store Present
[info   ] GLDriver: ARB Shader Atomic Counters Present
[info   ] GLDriver: ARB Shader Storage Buffer Object Present
[info   ] GLDriver: EXT Texture Compression S3TC Present
[info   ] GLDriver: ARB Uniform Buffer Object Present
[info   ] GLDriver: ARB Explicit Attrib Location Present
[info   ] GLDriver: EXT Texture Filter Anisotropic Present
[info   ] GLDriver: Geometry Shaders Present
[info   ] GLDriver: ARB Texture Buffer Object Present
[info   ] GLDriver: ARB Texture Swizzle Present
[info   ] GLDriver: ARB Pixel Buffer Object Present
[info   ] GLDriver: ARB Sampler Objects Present
[info   ] GLDriver: ARB Vertex Type 2_10_10_10_rev Present
[info   ] GLDriver: ARB Instanced Arrays Present
[info   ] SharedGPUObjects: Hardware Skinning enabled, method: TBO, max bones: 1024
[info   ] ShaderFilesManager: Compiling shader: /home/woutjuh/stk/stk-code/data/shaders/screenquad.vert
[info   ] ShaderFilesManager: Compiling shader: /home/woutjuh/stk/stk-code/data/shaders/motion_blur.frag
[info   ] ShaderFilesManager: Compiling shader: /home/woutjuh/stk/stk-code/data/shaders/lightning.frag
[info   ] ShaderFilesManager: Compiling shader: /home/woutjuh/stk/stk-code/data/shaders/primitive2dlist.vert
[info   ] ShaderFilesManager: Compiling shader: /home/woutjuh/stk/stk-code/data/shaders/transparent.frag
[info   ] ShaderFilesManager: Compiling shader: /home/woutjuh/stk/stk-code/data/shaders/texturedquad.vert
[info   ] ShaderFilesManager: Compiling shader: /home/woutjuh/stk/stk-code/data/shaders/uniformcolortexturedquad.frag
[info   ] ShaderFilesManager: Compiling shader: /home/woutjuh/stk/stk-code/data/shaders/texturedquad.frag
[info   ] ShaderFilesManager: Compiling shader: /home/woutjuh/stk/stk-code/data/shaders/coloredquad.vert
[info   ] ShaderFilesManager: Compiling shader: /home/woutjuh/stk/stk-code/data/shaders/coloredquad.frag
[info   ] ShaderFilesManager: Compiling shader: /home/woutjuh/stk/stk-code/data/shaders/colortexturedquad.vert
[info   ] ShaderFilesManager: Compiling shader: /home/woutjuh/stk/stk-code/data/shaders/colortexturedquad.frag
[info   ] irr_driver: GLSL supported.
[info   ] ShaderFilesManager: Compiling shader: /home/woutjuh/stk/stk-code/data/shaders/sp_pass.vert
[info   ] ShaderFilesManager: Compiling shader: /home/woutjuh/stk/stk-code/data/shaders/sp_solid.frag
[info   ] ShaderFilesManager: Compiling shader: /home/woutjuh/stk/stk-code/data/shaders/sp_shadow.vert
[info   ] ShaderFilesManager: Compiling shader: /home/woutjuh/stk/stk-code/data/shaders/white.frag
[info   ] ShaderFilesManager: Compiling shader: /home/woutjuh/stk/stk-code/data/shaders/sp_skinning.vert
[info   ] ShaderFilesManager: Compiling shader: /home/woutjuh/stk/stk-code/data/shaders/sp_skinning_shadow.vert
[info   ] ShaderFilesManager: Compiling shader: /home/woutjuh/stk/stk-code/data/shaders/sp_normal_map.frag
[info   ] ShaderFilesManager: Compiling shader: /home/woutjuh/stk/stk-code/data/shaders/sp_alpha_test.frag
[info   ] ShaderFilesManager: Compiling shader: /home/woutjuh/stk/stk-code/data/shaders/sp_shadow_alpha_test.frag
[info   ] ShaderFilesManager: Compiling shader: /home/woutjuh/stk/stk-code/data/shaders/sp_decal.frag
[info   ] ShaderFilesManager: Compiling shader: /home/woutjuh/stk/stk-code/data/shaders/sp_grass_pass.vert
[info   ] ShaderFilesManager: Compiling shader: /home/woutjuh/stk/stk-code/data/shaders/sp_grass.frag
[info   ] ShaderFilesManager: Compiling shader: /home/woutjuh/stk/stk-code/data/shaders/sp_grass_shadow.vert
[info   ] ShaderFilesManager: Compiling shader: /home/woutjuh/stk/stk-code/data/shaders/sp_unlit.frag
[info   ] ShaderFilesManager: Compiling shader: /home/woutjuh/stk/stk-code/data/shaders/sp_transparent.frag
[info   ] ShaderFilesManager: Compiling shader: /home/woutjuh/stk/stk-code/data/shaders/sp_ghost.frag
[info   ] ShaderFilesManager: Compiling shader: /home/woutjuh/stk/stk-code/data/shaders/sp_dynamic_night_bloom.frag
[info   ] ShaderFilesManager: Compiling shader: /home/woutjuh/stk/stk-code/data/shaders/sp_tilling_mitigation.frag
[info   ] ShaderFilesManager: Compiling shader: /home/woutjuh/stk/stk-code/data/shaders/sp_vertical_mapping.frag
[info   ] ShaderFilesManager: Compiling shader: /home/woutjuh/stk/stk-code/data/shaders/sp_road_blending.frag
[info   ] ShaderFilesManager: Compiling shader: /home/woutjuh/stk/stk-code/data/shaders/sp_displace.frag
[info   ] ShaderFilesManager: Compiling shader: /home/woutjuh/stk/stk-code/data/shaders/colorize.frag
[info   ] ShaderFilesManager: Compiling shader: /home/woutjuh/stk/stk-code/data/shaders/sp_normal_visualizer.vert
[info   ] ShaderFilesManager: Compiling shader: /home/woutjuh/stk/stk-code/data/shaders/sp_normal_visualizer.geom
[info   ] ShaderFilesManager: Compiling shader: /home/woutjuh/stk/stk-code/data/shaders/sp_normal_visualizer.frag
[info   ] GrandPrixManager: Loading Grand Prix files from data/grandprix/
[info   ] GrandPrixManager: Loading Grand Prix files from /home/woutjuh/.local/share/supertuxkart/grandprix/
[warn   ] SPMeshBuffer: kartDirt shader is missing, fallback to solid
[warn   ] SPMeshBuffer: kartDirt shader is missing, fallback to solid
[warn   ] SPMeshBuffer: kartDirt shader is missing, fallback to solid
[warn   ] SPMeshBuffer: kartDirt shader is missing, fallback to solid
[warn   ] SPMeshBuffer: kartDirt shader is missing, fallback to solid
[warn   ] LayoutManager: Statically sized widgets took all the place!!
[warn   ] LayoutManager: Statically sized widgets took all the place!!
[info   ] Singleton: Destroyed singleton.
[info   ] Singleton: Destroyed singleton.
[info   ] Singleton: Destroyed singleton.
[info   ] Singleton: Destroyed singleton.
[info   ] Singleton: Destroyed singleton.
[info   ] Singleton: Destroyed singleton.
[info   ] Singleton: Destroyed singleton.
[info   ] Singleton: Destroyed singleton.
[info   ] Singleton: Destroyed singleton.
[warn   ] irr_driver: The window size specified in user config is larger than your screen!
[info   ] IrrDriver: OpenGL version: 4.5
[info   ] IrrDriver: OpenGL vendor: X.Org
[info   ] IrrDriver: OpenGL renderer: Radeon RX Vega (VEGA10, DRM 3.27.0, 4.19.0-5-amd64, LLVM 8.0.1)
[info   ] IrrDriver: OpenGL version string: 4.5 (Core Profile) Mesa 19.1.2
[info   ] GLDriver: ARB Buffer Storage Present
[info   ] GLDriver: ARB Compute Shader Present
[info   ] GLDriver: ARB Arrays of Arrays Present
[info   ] GLDriver: ARB Texture Storage Present
[info   ] GLDriver: ARB Texture View Present
[info   ] GLDriver: ARB Image Load Store Present
[info   ] GLDriver: ARB Shader Atomic Counters Present
[info   ] GLDriver: ARB Shader Storage Buffer Object Present
[info   ] GLDriver: EXT Texture Compression S3TC Present
[info   ] GLDriver: ARB Uniform Buffer Object Present
[info   ] GLDriver: ARB Explicit Attrib Location Present
[info   ] GLDriver: EXT Texture Filter Anisotropic Present
[info   ] GLDriver: Geometry Shaders Present
[info   ] GLDriver: ARB Texture Buffer Object Present
[info   ] GLDriver: ARB Texture Swizzle Present
[info   ] GLDriver: ARB Pixel Buffer Object Present
[info   ] GLDriver: ARB Sampler Objects Present
[info   ] GLDriver: ARB Vertex Type 2_10_10_10_rev Present
[info   ] GLDriver: ARB Instanced Arrays Present
[info   ] SharedGPUObjects: Hardware Skinning enabled, method: TBO, max bones: 1024
[info   ] ShaderFilesManager: Compiling shader: /home/woutjuh/stk/stk-code/data/shaders/screenquad.vert
[info   ] ShaderFilesManager: Compiling shader: /home/woutjuh/stk/stk-code/data/shaders/motion_blur.frag
[info   ] ShaderFilesManager: Compiling shader: /home/woutjuh/stk/stk-code/data/shaders/lightning.frag
[info   ] ShaderFilesManager: Compiling shader: /home/woutjuh/stk/stk-code/data/shaders/primitive2dlist.vert
[info   ] ShaderFilesManager: Compiling shader: /home/woutjuh/stk/stk-code/data/shaders/transparent.frag
[info   ] ShaderFilesManager: Compiling shader: /home/woutjuh/stk/stk-code/data/shaders/texturedquad.vert
[info   ] ShaderFilesManager: Compiling shader: /home/woutjuh/stk/stk-code/data/shaders/uniformcolortexturedquad.frag
[info   ] ShaderFilesManager: Compiling shader: /home/woutjuh/stk/stk-code/data/shaders/texturedquad.frag
[info   ] ShaderFilesManager: Compiling shader: /home/woutjuh/stk/stk-code/data/shaders/coloredquad.vert
[info   ] ShaderFilesManager: Compiling shader: /home/woutjuh/stk/stk-code/data/shaders/coloredquad.frag
[info   ] ShaderFilesManager: Compiling shader: /home/woutjuh/stk/stk-code/data/shaders/colortexturedquad.vert
[info   ] ShaderFilesManager: Compiling shader: /home/woutjuh/stk/stk-code/data/shaders/colortexturedquad.frag
[info   ] irr_driver: GLSL supported.
[info   ] ShaderFilesManager: Compiling shader: /home/woutjuh/stk/stk-code/data/shaders/sp_pass.vert
[info   ] ShaderFilesManager: Compiling shader: /home/woutjuh/stk/stk-code/data/shaders/sp_solid.frag
[info   ] ShaderFilesManager: Compiling shader: /home/woutjuh/stk/stk-code/data/shaders/sp_shadow.vert
[info   ] ShaderFilesManager: Compiling shader: /home/woutjuh/stk/stk-code/data/shaders/white.frag
[info   ] ShaderFilesManager: Compiling shader: /home/woutjuh/stk/stk-code/data/shaders/sp_skinning.vert
[info   ] ShaderFilesManager: Compiling shader: /home/woutjuh/stk/stk-code/data/shaders/sp_skinning_shadow.vert
[info   ] ShaderFilesManager: Compiling shader: /home/woutjuh/stk/stk-code/data/shaders/sp_normal_map.frag
[info   ] ShaderFilesManager: Compiling shader: /home/woutjuh/stk/stk-code/data/shaders/sp_alpha_test.frag
[info   ] ShaderFilesManager: Compiling shader: /home/woutjuh/stk/stk-code/data/shaders/sp_shadow_alpha_test.frag
[info   ] ShaderFilesManager: Compiling shader: /home/woutjuh/stk/stk-code/data/shaders/sp_decal.frag
[info   ] ShaderFilesManager: Compiling shader: /home/woutjuh/stk/stk-code/data/shaders/sp_grass_pass.vert
[info   ] ShaderFilesManager: Compiling shader: /home/woutjuh/stk/stk-code/data/shaders/sp_grass.frag
[info   ] ShaderFilesManager: Compiling shader: /home/woutjuh/stk/stk-code/data/shaders/sp_grass_shadow.vert
[info   ] ShaderFilesManager: Compiling shader: /home/woutjuh/stk/stk-code/data/shaders/sp_unlit.frag
[info   ] ShaderFilesManager: Compiling shader: /home/woutjuh/stk/stk-code/data/shaders/sp_transparent.frag
[info   ] ShaderFilesManager: Compiling shader: /home/woutjuh/stk/stk-code/data/shaders/sp_ghost.frag
[info   ] ShaderFilesManager: Compiling shader: /home/woutjuh/stk/stk-code/data/shaders/sp_dynamic_night_bloom.frag
[info   ] ShaderFilesManager: Compiling shader: /home/woutjuh/stk/stk-code/data/shaders/sp_tilling_mitigation.frag
[info   ] ShaderFilesManager: Compiling shader: /home/woutjuh/stk/stk-code/data/shaders/sp_vertical_mapping.frag
[info   ] ShaderFilesManager: Compiling shader: /home/woutjuh/stk/stk-code/data/shaders/sp_road_blending.frag
[info   ] ShaderFilesManager: Compiling shader: /home/woutjuh/stk/stk-code/data/shaders/sp_displace.frag
[info   ] ShaderFilesManager: Compiling shader: /home/woutjuh/stk/stk-code/data/shaders/colorize.frag
[info   ] ShaderFilesManager: Compiling shader: /home/woutjuh/stk/stk-code/data/shaders/sp_normal_visualizer.vert
[info   ] ShaderFilesManager: Compiling shader: /home/woutjuh/stk/stk-code/data/shaders/sp_normal_visualizer.geom
[info   ] ShaderFilesManager: Compiling shader: /home/woutjuh/stk/stk-code/data/shaders/sp_normal_visualizer.frag
[warn   ] SPMeshBuffer: kartDirt shader is missing, fallback to solid
[warn   ] SPMeshBuffer: kartDirt shader is missing, fallback to solid
[warn   ] SPMeshBuffer: kartDirt shader is missing, fallback to solid
[warn   ] SPMeshBuffer: kartDirt shader is missing, fallback to solid
[warn   ] SPMeshBuffer: kartDirt shader is missing, fallback to solid
[warn   ] LayoutManager: Statically sized widgets took all the place!!
[info   ] Singleton: Destroyed singleton.
[info   ] Singleton: Destroyed singleton.
[info   ] Singleton: Destroyed singleton.
[info   ] Singleton: Destroyed singleton.
[info   ] Singleton: Destroyed singleton.
[info   ] Singleton: Destroyed singleton.
[info   ] Singleton: Destroyed singleton.
[info   ] Singleton: Destroyed singleton.
[info   ] Singleton: Destroyed singleton.
```

**Comment by glaubersm** [comment]
I use a single 1080p monitor on Arch Linux running KDE Plasma 5.17 Wayland session.
As we can see in the screenshot below, SuperTuxkart does not use the whole screen while in full screen mode. I can`t change the resolution from 1680x1050 to 1080p.
Supertuxkart tries to change to 1080p resoltution after I click on "Apply new resolution" button, but such resolution is not applied and 1680x1050 remains.

STK release version: 1.0

STK Source (PPA, distribution package, official binary, etc.): distribution package

System: Arch Linux

Graphics card: intel hd graphics

CPU: intel celeron G1820

**Comment by Benau** [comment]
wb9688 said it's fixed with sdl2! ![](https://cdn.lihkg.com/assets/faces/pig/free.gif)![](https://cdn.lihkg.com/assets/faces/pig/free.gif)![](https://cdn.lihkg.com/assets/faces/pig/free.gif)![](https://cdn.lihkg.com/assets/faces/pig/free.gif)![](https://cdn.lihkg.com/assets/faces/pig/free.gif)![](https://cdn.lihkg.com/assets/faces/pig/free.gif)

**Comment by glaubersm** [comment]
which version of sdl2 contains the fix?
I use supertuxkart 1.1 + sdl2 2.0.12 on Arch Linux and this bug persists.

**Comment by Dinesh0006** [comment]
Unsubscribe

**Comment by wb9688** [comment]
@glaubersm: SuperTuxKart started using SDL2 in some recent commits. Before that, STK wasn't using SDL yet, so you have to compile STK from source.

**Comment by glaubersm** [comment]
Thank you very much @wb9688.

**Comment by Benau** [comment]
btw not sure if @devnexen can test latest master and see if *BSD needs fixing compiliation after sdl2 is used ![](https://cdn.lihkg.com/assets/faces/pig/dance.gif)

**Comment by devnexen** [comment]
it works

**Comment by Benau** [comment]
good
