### ISSUE TITLE
Soccer ball will disappear when bringing STK into background

### ISSUE THREAD

**Issue by STK-FabianF** [supertuxkart/stk-code#4368]
## Description
In soccer mode, the ball or puck will disappear after STK is gone into background (done by e.g. opening another application "over" STK). This happens on both Windows and Android for me, so I assume it's not a device-related bug. The ball/puck can still be moved but stays invisible, and will appear again after a goal is scored.
![image](https://user-images.githubusercontent.com/70447655/91659681-a4131580-ead1-11ea-938c-89d422e280dc.png)

**Comment by Benau** [comment]
This should be fixed with https://github.com/supertuxkart/stk-code/commit/7f8ca9d4acb57418fe140435575a9c5845c8b9bd#diff-25d902c24283ab8cfbac54dfa101ad31 for android

**Comment by STK-FabianF** [comment]
At least on my Windows PC it still happened today, with 1.2.
